version: '3.7'
services:
  archway-dapp:
    container_name: archway-dapp
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - REACT_APP_CONTRACT_ADDRESS=0x0
    command: npm run start